### ISSUE TITLE
Joypad settings not being applied automatically if emulator is opened by associating it with a file type

### ISSUE THREAD

**Issue by circularfreezing** [LIJI32/SameBoy#142] opened 2019-01-11 19:24 UTC
If you open a rom by associating SameBoy with a file type, certain settings aren't applied unless you bring up the menu at least once. I tested some settings and it seems certain ones like which GameBoy you want to emulate or keyboard controls do work fine, but joypad settings do not. This is all using a natively supported Xbox One controller on windows if it helps.

**Comment by LIJI32** [comment] 2019-06-15 09:58
Duplicate of #131, the next release should include this fix.

**Closed by LIJI32** 2019-06-15 09:58 UTC
