### ISSUE TITLE
Real time clock doesn’t work

### ISSUE THREAD

**Issue by GeekyPlayzGH** [LIJI32/SameBoy#280] opened 2020-08-01 18:07 UTC
When playing Pokémon Gold, Silver, or Crystal, clock doesn't work like it should. Haven't tested other games, but I can assume it is a core-wide issue.

**Comment by tgsm** [comment] 2020-08-02 10:43
duplicate of #276

**Comment by GeekyPlayzGH** [comment] 2020-08-02 19:01
Has there been a fix?

**Closed** 2020-08-04 18:32 UTC
