### ISSUE TITLE
[Libretro] graphic glitches when using rewind and threaded video

### ISSUE THREAD

**Issue by xTMODx** [LIJI32/SameBoy#110] opened 2018-08-30 15:34 UTC
I am getting graphical glitches when releasing the rewind button and threaded video setting on when i quickload the glitch is away again until i rewind again
https://www.youtube.com/watch?v=78_15NhEhPs
also when disabling VSYNC it crash when i try to rewind
I am using the newest nightly 1.7.4 64bit and latest core on my Galaxy Note 8

**Comment by LIJI32** [comment] 2018-09-01 21:00
Duplicate of #42 and libretro/RetroArch#6382 – this bug seems to be in RetroArch's code.

**Closed by LIJI32** 2018-09-01 21:00 UTC
