### ISSUE TITLE
Can't Link with Same Game in RetroArch Core

### ISSUE THREAD

**Issue by TradeDraft** [LIJI32/SameBoy#40] opened 2018-03-07 01:43 UTC
I tried something last night.

That IF you load the Same Game Up then it will not work at all. Only Works when you have 2 DIfferent Games in the 2 Gameboys.

Video I made Here:

https://www.youtube.com/watch?v=6nspM67aQzU

I guess Using the Same Game when Trading it kind of Stupid but IF you playing 2 Player with the game you can’t.

**Comment by fr500** [comment] 2018-03-07 04:28
FWIW I tried the same:

https://www.youtube.com/watch?v=ZpCH9xYN1co

And it worked just fine...

**Comment by TradeDraft** [comment] 2018-03-07 05:49
I tried Pokemon Gold Too but did not Work:

https://www.youtube.com/watch?v=nim9c0Z8ztc&feature=youtu.be

Save Here:

https://www.sendspace.com/file/k5u75h

**Comment by TradeDraft** [comment] 2018-03-07 10:19
Okay I tried with getting the Latest .info.

No only the 1st Gameboy has a Save File while the 2nd Gameboy has no Save.

How do I fix that?

Like Here when I did it:

https://www.youtube.com/watch?v=e1H9Mmohc8w&feature=youtu.be

**Comment by TradeDraft** [comment] 2018-03-07 10:58
So Can't Deleate the 1 above I relised I did not use the GameLink Sorry about that

**Comment by fr500** [comment] 2018-03-07 14:56
Just thought worth mentioning, I can't reproduce these issues.

**Comment by fr500** [comment] 2018-03-20 07:06
@LIJI32 close this, it was a user issue

**Comment by TradeDraft** [comment] 2018-03-20 07:30
Yeah. Found out it was because I used same Gamepad for Both Gameboys

**Closed** 2018-03-20 09:15 UTC
