### ISSUE TITLE
Laggy and choppy audio

### ISSUE THREAD

**Issue by SuperDisk** [LIJI32/SameBoy#180] opened 2019-05-16 00:27 UTC
This is pretty odd, because SameBoy used to produce correct audio until today.

Here's a video showing the issue:
https://www.youtube.com/watch?v=haU5e7wV7nU

No idea why this would occur out of the blue. I tried restarting my computer in case it was a screwed up sound driver or something but nope.

**Comment by LIJI32** [comment] 2019-05-17 17:28
Does this occur with older versions of SameBoy known to work on your machine?

**Comment by RokkumanX** [comment] 2019-05-18 09:10
@LIJI32 
Could this also be related to issue #161?

I remember some time ago reading about #8, #19 and #125

**Comment by LIJI32** [comment] 2019-05-18 09:59
I haven't checked #161 yet so it might be related. #8 is old and irrelevant, the other two are emulation inaccuracies that have been fixed. In the video it appears that SameBoy runs in a slightly lower frame rate, and since I don't interpolate audio on such cases it sounds choppy. So it's either I introduced some major performance regression to the Windows port, or some configuration change with @SuperDisk's machine is making SameBoy slower.

**Comment by SuperDisk** [comment] 2019-05-19 21:03
Using the same version as the one I showed in the video today, SameBoy is now running at the correct framerate and with no audio issues. Pretty strange, I'll let you know if I find out anything else. I think it might have something to do with having my laptop being connected to an monitor via the Razor Core, which has an external video card in it.

**Comment by LIJI32** [comment] 2019-05-19 21:24
Closing this for now as it appears to be a local configuration issue. Feel free to reopen if it happens again.

**Comment by SuperDisk** [comment] 2019-06-16 22:12
I can reliably reproduce the issue only when the Razer Core is connected, and can't when it's not. So this seems to be some sort of weird issue with the Core. Just throwing that out there in case anyone else comes across the same issue.

**Comment by LIJI32** [comment] 2019-06-17 21:08
I'll reopen this issue in case anyone has an idea what it could be. Sadly, it's not an issue I can debug as I cannot reproduce it (I don't have neither a Razer Core nor a Windows PC to connect it to). However, could it be that your monitor is configured to 50Hz?

**Comment by LazyBumHorse** [comment] 2019-06-22 11:28
I get this in winsdl 0.12 (on Windows 7), 0.11.2 does work for me.

**Comment by LIJI32** [comment] 2019-06-22 14:25
Is only the sound choppy, or is the frame rate also lower than usual? What is the refresh rate of your display?

**Comment by LazyBumHorse** [comment] 2019-06-22 14:35
60hz monitor, very stable 60 fps according to Afterburner (did try without as well):
![stable60](https://user-images.githubusercontent.com/31176526/59965225-6c8efd80-950b-11e9-8676-46fd22980e75.png)

**Comment by LIJI32** [comment] 2019-06-22 14:36
Interesting. I can reproduce this on my VM, seems like yet another SDL audio issue. I'll try to get it fixed.

**Comment by poesdelal** [comment] 2019-06-24 16:21
Audio still not fixed in 0.12.1

**Comment by LazyBumHorse** [comment] 2019-06-24 17:43
0.12.1 did fix the issue for me.

**Comment by TUREVARSKI** [comment] 2019-06-25 14:05
I’m also still having the issue in 0.12.1 winsdl. I’ll happily help by providing testing/system information if you want me to.

**Comment by poesdelal** [comment] 2019-09-15 05:53
Finally audio fixed in 0.12.2 winsdl

**Closed** 2020-03-27 15:51 UTC
