### ISSUE TITLE
Cocoa v0.13.3 Cannot Open Files in GameBoy ROM Format

### ISSUE THREAD

**Issue by TRIFORCE89** [LIJI32/SameBoy#275] opened 2020-07-01 00:12 UTC
New to SameBoy, but not to emulation. Trying out the recent v0.13.3 Cocoa release on Mac. Upon launch I get a file open dialogue - but if I navigate to a folder of .gb ROMs they are all greyed out and can't be selected. If I close that dialogue and instead drag a .gb file over onto SameBoy in my Dock I get a prompt that:

The document "filename.gb" could not be opened. SameBoy cannot open files in the "GameBoy ROM" format.

Are there instructions I need to follow to get this working? It is currently configured to use the built-in boot ROMs.

**Comment by NieDzejkob** [comment] 2020-07-01 00:15
This might be a duplicate of #263.

**Comment by LIJI32** [comment] 2020-07-01 00:17
Indeed it is, try removing Visual Boy Advance and execute the terminal command in that issue. Sadly it's a bug with macOS itself and there's nothing I can do to fix it.

**Closed by LIJI32** 2020-07-01 00:17 UTC

**Comment by TRIFORCE89** [comment] 2020-07-01 03:23
Ah, I see. Thank you! What a quirk.
